import { Header } from '@/component/header'
import './globals.css'
import { Inter } from 'next/font/google'
import { Menu } from '@/component/menu'
import Footer from '@/component/footer'
import 'bootstrap/dist/css/bootstrap.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Menu />
        {children}
        <Footer />
      </body>
    </html>
  )
}
